### PR TITLE
Add support for up to 13.2.0

### LINKED ISSUE #9: Doesn't work in latest atmosphere
Bitmap Printer isnt working in atmosphere 19.1 I'm on firmware version 12.0.1 right now.

### PR DESCRIPTION
**Pull request by ThatNintendoNerd**
Closes #9 and #10. Latest patch tested on HOS 13.2.0 with Atmosphère 1.2.5.

### CODE REVIEW

**Comment by LunaDook** [comment]
Does this also work for 13.2.1?

**Comment by ThatNintendoNerd** [comment]
> Does this also work for 13.2.1?

Yes, as the system module being patched has not been updated since 13.0.0. The build ID for it was not changed and its main executable was not touched either, allowing the 13.0.0 IPS patch to work on any subsequent firmwares until it gets updated.

**Comment by LunaDook** [comment]
I tried using these patches which seem to have been somehow retroactively added to 1.2.0 release under the releases tab (I can see the new .ips files in the vi_patches folder in the release), but testing on 13.2.1 I cannot seem to get it working. Not entirely sure what I'm doing wrong. Any advice?

**Comment by ThatNintendoNerd** [comment]
> I tried using these patches which seem to have been somehow retroactively added to 1.2.0 release under the releases tab (I can see the new .ips files in the vi_patches folder in the release), but testing on 13.2.1 I cannot seem to get it working. Not entirely sure what I'm doing wrong. Any advice?

I have just confirmed on 13.2.1 that both the bitmap-printer sysmodule and the corresponding IPS patch function as intended: outputting a valid BMP file to `sd:/Nintendo/Album/Bitmaps/`. If this is your first time using this homebrew software, there will be no clear indication that a screenshot was taken, but it will output to the aforementioned directory. Otherwise, I'd suggest any further help be taken to Discord, either by joining and/or asking in a server offering Switch modding help, or you may contact me directly at `ThatNintendoNerd#3684`

EDIT: The new patches never made their way onto the user's microSD card. Additionally, they were using an emuMMC, so the new screenshot directory was redirected to inside of the `Nintendo` folder somewhere in the `sd:/emuMMC/` directory.

**Comment by HookedBehemoth** [comment]
Do you think you could port the patch for 15.0.0 too?

**Comment by HookedBehemoth** [comment]
nvmnd did it myself now

**Pull request merged**
